### ISSUE TITLE
Got a few Questions :)

### ISSUE THREAD

**Issue by Mandalorian007** [jhernandez6354/ql_entanglement#1]
@jhernandez6354 Hey been using your code as a reference for a community project I am working on, but I haven't figured out which token is required for the login process. I'd love to chat with you a bit about this project if possible, but I was unable to find an email address or discord account to reach out to you on :)

**Comment by jhernandez6354** [comment]
Sorry mate, I didn't noticed you commented.  The token was the tricky part, and I don't have an apple device to test on to figure out how to get the token for that. For android, the token is used for any game that connects to the play store.  I used the questland logs to pull the token which, but if you have an http sniffer, that should work as well, since most of the calls are made through a ReST API. You can hit me up on discord at Tenjin#8698

**Comment by Mandalorian007** [comment]
Awesome sent you an invite on discord let's chat :)
